#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weather.Resource", IsApplication=true)]

namespace Weather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Akershus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Aust_Agder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Buskerud = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Finnmark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Hedmark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Hordaland = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Moere_og_Romsdal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Nord_Troendelag = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Nordland = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Oestfold = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Oppland = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Oslo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Rogaland = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Soer_Troendelag = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Sogn_og_Fjordane = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Telemark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Troms = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Vest_Agder = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Vestfold = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int lastWeek = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int loadingPanel = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int selectStation = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int selectedStationLabel = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SelectStationLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
